import { ThemeProvider } from "next-themes";
import {Plus_Jakarta_Sans} from "next/font/google"
import type { Metadata } from "next";import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const plus_jakarta_sans = Plus_Jakarta_Sans({
  subsets: ["latin"]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={plus_jakarta_sans.className}>
        <ThemeProvider attribute="class" defaultTheme="light">
          {children}
        </ThemeProvider>  
      </body>
    </html>
  );
}

